server:
  port: 9091
spring:
  application:
    name: user-center
  datasource:
    url: jdbc:mysql://localhost:3306/rbac?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    hikari:
      username: root
      password: yibo
      # mysql 6.x以上 com.mysql.cj.jdbc.Driver
      # mysql 5.x com.mysql.jdbc.Driver
      driver-class-name: com.mysql.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: 784ade72-a3f0-4802-8c44-287376030069
      config:
        server-addr: 127.0.0.1:8848
        namespace: 784ade72-a3f0-4802-8c44-287376030069
        file-extension: yaml
        # 支持多个共享dataId的配置，优先级小于extension-configs,shared-configs是一个集合
        shared-configs[0]:
          # redis RrocketMQ等通用配置可以定义在这个里面
          dataId: gateway-common.yaml # 配置文件名dataId
          group: DEFAULT_GROUP  # 默认为DEFAULT_GROUP
          refresh: true # 是否动态刷新,默认为false